version:     "1--12 September 2021"
copyright:   "2021"
description:
  Hi! Welcome to Nicholas "nichoje" Jonathan Kinandana's OS 212 Github Page
disclaimer:
  This page is based on GSGS so...
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "Zip File"
  link:      "/template.zip"
- navbar:    "TarBall"
  link:      "/template.tar.bz2"
- navbar:    "GitHub"
  link:      "https://github.com/ThisIsHowMeDoIt/template/"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://template.vlsm.org/"
title:       "nichoje's Github Page"
lang:        "en-US"
author:      "Nicholas Jonathan Kinandana"
address:     "South Jakarta"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"


